// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserRequest struct {
	Email                string          `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Metadata             *_struct.Struct `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddUserRequest) GetMetadata() *_struct.Struct {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type UpdateUserRequest struct {
	User                 *User                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type User struct {
	// Id uniquely identifies a user. Output only.
	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Output only.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only.
	Metadata             *_struct.Struct `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetMetadata() *_struct.Struct {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*AddUserRequest)(nil), "example.AddUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "example.GetUserRequest")
	proto.RegisterType((*ListUsersRequest)(nil), "example.ListUsersRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "example.UpdateUserRequest")
	proto.RegisterType((*User)(nil), "example.User")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xd3, 0x94, 0xd2, 0x8d, 0x52, 0x60, 0x55, 0xf5, 0xc7, 0x2a, 0xb0, 0x98, 0x4b, 0x55,
	0x11, 0xbb, 0x4d, 0x39, 0x35, 0xe2, 0x60, 0x8a, 0xa8, 0x8a, 0x40, 0x42, 0x29, 0xbd, 0xb4, 0x07,
	0xb4, 0x8e, 0x27, 0xce, 0x52, 0xdb, 0x6b, 0x76, 0x37, 0x2d, 0x55, 0xe9, 0x05, 0xce, 0x5c, 0x02,
	0x67, 0x9e, 0x82, 0x03, 0xef, 0xc1, 0x2b, 0xf0, 0x20, 0xc8, 0x6b, 0x3b, 0x89, 0x1d, 0x21, 0x21,
	0x4e, 0xde, 0xd9, 0xf9, 0x66, 0xbe, 0xcf, 0xdf, 0x8c, 0x8d, 0x9a, 0xf0, 0x81, 0x46, 0x49, 0x08,
	0x76, 0x22, 0xb8, 0xe2, 0x78, 0x21, 0x0f, 0xcd, 0xfb, 0x01, 0xe7, 0x41, 0x08, 0x8e, 0xbe, 0xf6,
	0x86, 0x7d, 0x47, 0xb1, 0x08, 0xa4, 0xa2, 0x51, 0x92, 0x21, 0xcd, 0x8d, 0x2a, 0x40, 0x2a, 0x31,
	0xec, 0xa9, 0x3c, 0x4b, 0xaa, 0xd9, 0x3e, 0x83, 0xd0, 0x7f, 0x1b, 0x51, 0x79, 0x56, 0xa9, 0xa7,
	0x09, 0x73, 0x68, 0x1c, 0x73, 0x45, 0x15, 0xe3, 0xb1, 0xcc, 0xb3, 0x8f, 0xf4, 0xa3, 0xd7, 0x0a,
	0x20, 0x6e, 0xc9, 0x0b, 0x1a, 0x04, 0x20, 0x1c, 0x9e, 0x68, 0xc4, 0x2c, 0xda, 0x3a, 0x45, 0x4b,
	0xae, 0xef, 0x1f, 0x4b, 0x10, 0x5d, 0x78, 0x3f, 0x04, 0xa9, 0xf0, 0x32, 0x9a, 0x87, 0x88, 0xb2,
	0x70, 0xcd, 0x20, 0xc6, 0xe6, 0x62, 0x37, 0x0b, 0xf0, 0x2e, 0xba, 0x19, 0x81, 0xa2, 0x3e, 0x55,
	0x74, 0xad, 0x46, 0x8c, 0xcd, 0x46, 0x7b, 0xd5, 0xce, 0x64, 0xd8, 0x85, 0x50, 0xfb, 0x48, 0xbf,
	0x46, 0x77, 0x0c, 0xb4, 0x08, 0x5a, 0x3a, 0x00, 0x35, 0xdd, 0x7c, 0x09, 0xd5, 0x98, 0x9f, 0x77,
	0xae, 0x31, 0xdf, 0xc2, 0xe8, 0xf6, 0x4b, 0x26, 0x35, 0x44, 0xe6, 0x18, 0x4b, 0xa2, 0x3b, 0xc7,
	0x89, 0x4f, 0x15, 0x4c, 0x17, 0x3e, 0x40, 0xf5, 0xa1, 0x04, 0xa1, 0x4b, 0x1b, 0xed, 0xa6, 0x5d,
	0x78, 0xaf, 0x31, 0x3a, 0x85, 0x3b, 0xa8, 0x31, 0xd4, 0x75, 0xda, 0xab, 0x5c, 0xa5, 0x39, 0xa3,
	0xf2, 0x79, 0x6a, 0xe7, 0x2b, 0x2a, 0xcf, 0xba, 0x28, 0x83, 0xa7, 0x67, 0xeb, 0xbb, 0x81, 0xea,
	0x69, 0xaf, 0xaa, 0xc2, 0x89, 0x1d, 0xb5, 0x69, 0x3b, 0x3a, 0xa8, 0xd1, 0x13, 0x90, 0x72, 0xa5,
	0xc3, 0x5d, 0x9b, 0xfb, 0x0b, 0xd7, 0x9b, 0x62, 0xf2, 0x5d, 0x94, 0xc1, 0xd3, 0x8b, 0x92, 0x97,
	0xf5, 0x7f, 0xf4, 0xb2, 0xfd, 0xb3, 0x8e, 0x1a, 0xa9, 0xc0, 0x23, 0x10, 0xe7, 0xac, 0x07, 0xf8,
	0x23, 0x5a, 0xc8, 0x07, 0x87, 0x57, 0xc7, 0x6e, 0x94, 0x47, 0x69, 0x96, 0x6d, 0xb2, 0x0e, 0x47,
	0xae, 0x8d, 0xe6, 0xb5, 0xd7, 0x18, 0xb9, 0xbe, 0x4f, 0x28, 0x49, 0x8d, 0x33, 0xd7, 0x27, 0x67,
	0xa2, 0x38, 0x51, 0x03, 0x20, 0x12, 0xc4, 0x39, 0x08, 0xfb, 0xd3, 0xaf, 0xdf, 0x5f, 0x6b, 0xd8,
	0x6a, 0xea, 0x55, 0x3b, 0xdf, 0x71, 0x52, 0x88, 0xdc, 0x33, 0xb6, 0xf0, 0x17, 0x03, 0x2d, 0xe4,
	0xa3, 0x9d, 0xa2, 0x2f, 0x0f, 0xbb, 0x4a, 0x7f, 0x32, 0x72, 0x9f, 0x14, 0xf4, 0x2b, 0x07, 0xa0,
	0x0a, 0x4a, 0xef, 0x32, 0xa5, 0x64, 0x82, 0x1c, 0x3e, 0x33, 0x37, 0x0e, 0x40, 0xc9, 0x22, 0xd1,
	0x17, 0x3c, 0x9a, 0x51, 0xb3, 0x8c, 0x71, 0x49, 0x8d, 0x73, 0xc5, 0xfc, 0x6b, 0xfc, 0xd9, 0x40,
	0x8b, 0xe3, 0x45, 0xc2, 0xeb, 0x63, 0xe2, 0xea, 0x72, 0x55, 0x35, 0xbd, 0x18, 0xb9, 0xed, 0xb1,
	0x25, 0x29, 0x58, 0x33, 0x4b, 0xf3, 0xae, 0x3e, 0xd3, 0x30, 0xcc, 0x62, 0xc2, 0xe3, 0x19, 0x21,
	0xb7, 0x70, 0xd9, 0x96, 0x6d, 0x03, 0x7f, 0x33, 0x10, 0x9a, 0xac, 0x2e, 0x36, 0x27, 0x5c, 0xd5,
	0x7d, 0xae, 0xea, 0x38, 0x1d, 0xb9, 0x8f, 0x0b, 0x1d, 0xcd, 0x0c, 0x5d, 0x4c, 0x67, 0x63, 0x7f,
	0x40, 0xe3, 0x00, 0x48, 0x22, 0x78, 0x02, 0x42, 0x31, 0x90, 0x84, 0xf7, 0xf3, 0x64, 0xa6, 0xe4,
	0x5e, 0x7b, 0x65, 0x5a, 0x89, 0x73, 0xa5, 0x53, 0xcc, 0xbf, 0xde, 0xd3, 0x1f, 0xc6, 0xd3, 0x1f,
	0xc6, 0xc8, 0x8d, 0xf1, 0x7c, 0x7b, 0x6e, 0xc7, 0xde, 0xde, 0x32, 0x6a, 0xc2, 0x43, 0x0f, 0x83,
	0xee, 0xeb, 0xfd, 0x56, 0x40, 0x15, 0x5c, 0xd0, 0x4b, 0xe2, 0x71, 0x16, 0x82, 0x48, 0xc2, 0x94,
	0x54, 0x40, 0xc2, 0x25, 0x53, 0x5c, 0x5c, 0xe2, 0xce, 0x40, 0xa9, 0x44, 0xee, 0x39, 0x4e, 0xc0,
	0xd4, 0x60, 0xe8, 0xd9, 0x3d, 0x1e, 0x39, 0xef, 0xf8, 0x80, 0xc6, 0x9e, 0xa0, 0xb1, 0x3f, 0xe0,
	0x42, 0x2a, 0x27, 0x10, 0x49, 0xaf, 0xe8, 0xd3, 0x9a, 0xea, 0x73, 0xe2, 0xfe, 0x47, 0x51, 0xf6,
	0xcb, 0xeb, 0xe4, 0xc6, 0x78, 0x37, 0x74, 0xb8, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x17, 0x3a,
	0x7a, 0x9b, 0x68, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (UserService_ListUsersClient, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/example.UserService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/example.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (UserService_ListUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserService_serviceDesc.Streams[0], "/example.UserService/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ListUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceListUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceListUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/example.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	AddUser(context.Context, *AddUserRequest) (*User, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	ListUsers(*ListUsersRequest, UserService_ListUsersServer) error
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) AddUser(ctx context.Context, req *AddUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) ListUsers(req *ListUsersRequest, srv UserService_ListUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ListUsers(m, &userServiceListUsersServer{stream})
}

type UserService_ListUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceListUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceListUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserService_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example.proto",
}
